site_name: Brent Oil Analysis
site_description: Bayesian Change Point Analysis of Brent Oil Prices
site_url: https://hann2004.github.io/brent-analysis

theme:
  name: material
  # Add this for slightly faster rendering
  features:
    - navigation.instant  # Faster page loads
    - navigation.tracking  # Auto-highlight current page

plugins:
  - search
  - mkdocs-jupyter:
      include_source: true
      execute: false
    

nav:
  - Home: index.md
  - Task 1: methodology.md
  - Task 2: results.md
  - Time Series Implementation: results.md#time-series-implementation
  - Change Point Model: results.md#change-point-model
  - Code Quality: methodology.md#code-quality
  # Dev note: ensure clean working tree (git status), then `git pull --rebase origin task-2`
  - Notebooks:
    - Events: notebooks/00_event.ipynb
    - Time Series EDA (Task 2): notebooks/01_eda.ipynb
    - Bayesian Model (Task 2): notebooks/02_bayesian_model.ipynb